DROP DATABASE IF EXISTS hotel;
CREATE DATABASE hotel;
USE hotel;

CREATE TABLE reserve (
	id INT NOT NULL AUTO_INCREMENT,
	checkin_date DATE NOT NULL,
	checkout_date DATE NOT NULL,
	value DECIMAL(15,2) NOT NULL,
	payment_method VARCHAR(50),
	PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE guest (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	lastname VARCHAR(50) NOT NULL,
	birthdate DATE,
	nationality VARCHAR(50),
	phone_number VARCHAR(50) NOT NULL,
	id_reserve INT NOT NULL,
	PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE employee (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	lastname VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
	PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE hotel.guest ADD FOREIGN KEY (id_reserve) REFERENCES hotel.reserve(id) ON DELETE CASCADE;
